'use strict';
// paneRuntime.js — what a column accepts from the DM shell in two-map mode. panes.js is the
// shell's half of the same conversation.
//
// A column is an ordinary DM instance with its chrome hidden, so every message below simply
// presses the control this instance already has. Nothing here re-implements a behaviour.
//
// THE SET IS GENERATED BY ONE RULE: one message per control the parent's chrome owns that calls a
// function in the same document - every #btn-* and every input in #tools-wrapper and #sidebar-right,
// plus the advanced fog panel those open. A pick-one group is one message carrying a value. Four
// controls send nothing: #btn-help, the minimap, Open Window, Fullscreen.
const PANE_CONTROLS = {
  // ⚠ REPORTS THE OUTCOME: switchScene swallows a bad map and recovers onto the previous scene,
  // and a wrong record makes the library refuse that map in the other column.
  'pane-load-scene': m => {
    switchScene(m.sceneId).catch(console.error).then(() => {
      if (parent === window) return;
      parent.postMessage({ type: 'pane-scene-result', pane: paneId,
                           sceneId: currentScene ? currentScene.id : null }, '*');
    });
  },
  'pane-refit':      () => { resizeViewport(); viewportDirty = true; scheduleRender(); },
  // ⚠ syncSize FIRST: the column's own resize event may land either side of this message.
  'pane-adopt-view': m => { syncSize(); applyCamera(m.view); viewportDirty = true; scheduleRender(); },

  'pane-paint-direction': m => setPaintDirection(m.dir),
  'pane-shape':           m => setShape(m.shape),
  'pane-shape-op':        m => setShapeOp(m.op),
  'pane-place-mode':      m => setPlaceMode(m.mode),
  'pane-material':        m => setMaterial(m.material),
  'pane-snap':            m => { snapToGrid = m.on; _paneToggle('btn-snap', m.on); },
  'pane-axislock':        m => { axisLock = m.on; _paneToggle('btn-axislock', m.on); },
  'pane-brush-size':      m => { brushSize = m.size; },
  'pane-door-size':       m => _paneField(m.id, m.value, 'change'),
  // ⚠ `input`, not `change`: that field is wired to oninput and ignores change entirely.
  'pane-corner-radius':   m => _paneField('fx-radius-num', m.radius, 'input'),

  'pane-reveal-all':  () => revealAllRooms(),
  'pane-shroud-all':  () => shroudAllRooms(),
  'pane-floorplan':   () => drawStoredFloorPlan(),
  // ⚠ The push to the TV goes with them: the picker's own handler runs in the DM window, which
  // has no Player of its own while two maps are up.
  'pane-fog-color':   m => { applyFogColor(m.pickedHex); syncFogColorToPlayer(m.pickedHex); },
  'pane-fog-tint':    m => { applyFogTintAlpha(m.alpha); syncFogColorToPlayer(fogPickedHex); },
  'pane-fog-feather': m => _paneField('fog-feather-num', m.radius, 'change'),
  'pane-fog-half':    m => _paneField('fog-half-alpha-num', m.pct, 'change'),
  'pane-anim':        m => applyPaneAnimParams(m),

  'pane-grid':      m => { applyGridConfig(m.config); commitGridChange(); },
  'pane-calibrate': m => armGridCalibration(!!m.on),

  // The Player pane. Each column drives its OWN Player window through its own controls.
  'pane-sync-view':         () => _paneClick('btn-sync-view'),
  'pane-send':              () => sendToPlayer(),
  'pane-auto-sync':         m => { if (autoSync !== m.on) _paneClick('btn-auto-sync'); },
  'pane-player-lock':       m => {
    minimapLocked = m.locked;
    if (playerWindow && !playerWindow.closed) {
      playerWindow.postMessage({ type: 'player-lock', locked: minimapLocked }, '*');
    }
  },
  'pane-player-view': m => {
    minimapSetView(m.view);
    if (playerWindow && !playerWindow.closed) {
      playerWindow.postMessage({ type: 'view-snap', ...m.view }, '*');
    }
  },
};

function _paneToggle(id, on) {
  const el = document.getElementById(id);
  if (el) el.classList.toggle('active', !!on);
}

// ⚠ Replays the control: these values are applied by a handler closed over their own field, so
// writing the variable alone skips the rebuild that follows.
function _paneField(id, value, evt) {
  const el = document.getElementById(id);
  if (!el) return;
  el.value = value;
  el.dispatchEvent(new Event(evt, { bubbles: true }));
}

function _paneClick(id) {
  const el = document.getElementById(id);
  if (el) el.click();
}

// One message carries every animation parameter, because every control that changes one ends in
// syncAnimToPlayer. A warp change alone rebuilds the frames. The Player's copy is playerMessages.js.
function applyPaneAnimParams(m) {
  const warpChanged = (m.cloudWarpStrength != null && m.cloudWarpStrength !== cloudWarpStrength)
                   || (m.cloudWarpRadius   != null && m.cloudWarpRadius   !== cloudWarpRadius);
  fogAnimSpeed      = m.fogAnimSpeed      ?? fogAnimSpeed;
  driftScale        = m.driftScale        ?? driftScale;
  cloudFrameSpeed   = m.cloudFrameSpeed   ?? cloudFrameSpeed;
  alphaPulseAmp     = m.alphaPulseAmp     ?? alphaPulseAmp;
  cloudWarpStrength = m.cloudWarpStrength ?? cloudWarpStrength;
  cloudWarpRadius   = m.cloudWarpRadius   ?? cloudWarpRadius;
  fogAnimEnabled    = m.fogAnimEnabled    ?? fogAnimEnabled;
  _paneToggle('btn-anim', fogAnimEnabled);
  if (fogAnimEnabled) startFogAnim(); else stopFogAnim();
  if (warpChanged) regenCloudFrames(); else syncAnimToPlayer();
}

function initPane() {
  reportPaneClicks();
  if (parent !== window) parent.postMessage({ type: 'pane-hello', pane: paneId }, '*');
  // A column opened empty has no scene menu of its own, so the card cannot tell the DM to use one.
  if (!new URLSearchParams(location.search).get('scene')) {
    const line = landing && landing.querySelector('p');
    if (line) line.innerHTML = 'Pick a map from <strong>Scenes</strong>';
  }
  window.addEventListener('message', e => {
    const msg = e.data;
    if (!msg || !msg.type) return;
    const handler = PANE_CONTROLS[msg.type];
    if (handler) handler(msg);
  });
}
