'use strict';
// Player-mode runtime: cloud-texture pre-gen, the PLAYER_READY handshake, resize, the DM message
// handler and player pan/zoom. Called once from index.html in player mode.

// _playerVideoGen bails a blob read that resolved after a newer switch. _playerPendingVideo is
// the <video> still loading, which ⚠ cleanupVideo() CANNOT SEE: a push overtaking it revokes the
// blob URL under an element still reading it, and Chromium reports net::ERR_FILE_NOT_FOUND while
// the newer push paints its own map. Stop that load first, then let cleanupVideo revoke.
var _playerVideoGen = 0;
var _playerPendingVideo = null;

function dropPendingPlayerVideo() {
  const v = _playerPendingVideo;
  _playerPendingVideo = null;
  if (!v) return;
  v.onerror = null; v.oncanplay = null; v.onseeked = null;
  v.pause();
  // removeAttribute + load(), never src = '': an empty src sends the element after the document.
  v.removeAttribute('src');
  v.load();
  if (v.parentNode) v.parentNode.removeChild(v);
}

// ⚠ STARTS ON THE DM'S FIRST WORD, NEVER AT INIT. A pre-warmed window sits unheld, and a retry
// through that lands a `need-map` the DM accepts on adoption, blanking the players' fog.
var _playerRetryStarted = false;
function startPlayerMapRetryOnce() {
  if (_playerRetryStarted) return;
  _playerRetryStarted = true;
  initPlayerMapRetry();   // viewport.js: need-map to the DM until a map arrives
}

// The card's backdrop while the first map decodes: the app's own fog, drifting. Its own loop,
// because the render pipeline has no map to draw and does nothing on these frames.
var _loadingFogRaf = null;
function startLoadingFog() {
  if (_loadingFogRaf || !landing) return;
  landing.classList.add('loading');
  startFogAnim();   // fog.js: what advances the drift and morph this reads
  const cv = document.getElementById('landing-fog');
  if (!cv) return;
  const ctx = cv.getContext('2d');
  const tick = () => {
    const w = landing.clientWidth, h = landing.clientHeight;
    if (cv.width !== w || cv.height !== h) { cv.width = w; cv.height = h; }
    drawLoadingFog(ctx, w, h);
    _loadingFogRaf = requestAnimationFrame(tick);
  };
  _loadingFogRaf = requestAnimationFrame(tick);
}

// Called from revealPlayer() when the cover lifts. ⚠ THE LOOP AND THE LOADING LINE STOP EVEN WITH
// NO MAP: the error paths reveal too, and a map that never decodes would leave the TV reading
// "Loading map…" all session. The card goes only when there IS a map.
function onPlayerMapShown() {
  if (!landing) return;
  if (_loadingFogRaf) { cancelAnimationFrame(_loadingFogRaf); _loadingFogRaf = null; }
  landing.classList.remove('loading');
  if (mapOffscreen) landing.style.display = 'none';
}

// ─── Pane runtime ────────────────────────────────────────────────────────────
// A column is an ordinary DM instance with its chrome hidden, so every message below simply
// presses the control this instance already has. Nothing here re-implements a behaviour.
//
// THE SET IS GENERATED BY ONE RULE: one message per control the parent's chrome owns that today
// calls a function in the same document - every #btn-* and every input in #tools-wrapper and
// #sidebar-right, plus the advanced fog panel those open. That is 66 controls collapsing to the
// 27 below, because a pick-one group is one message with a value and several controls already
// funnel into one function. Four send nothing: #btn-help, the minimap, Open Window, Fullscreen.
const PANE_CONTROLS = {
  // ⚠ REPORTS THE OUTCOME: switchScene swallows a bad map and recovers onto the previous scene,
  // and a wrong record makes the library refuse that map in the other column.
  'pane-load-scene': m => {
    switchScene(m.sceneId).catch(console.error).then(() => {
      if (parent === window) return;
      parent.postMessage({ type: 'pane-scene-result', pane: paneId,
                           sceneId: currentScene ? currentScene.id : null }, '*');
    });
  },
  'pane-refit':      () => { syncSize(); fitToScreen(); viewportDirty = true; scheduleRender(); },

  'pane-paint-direction': m => setPaintDirection(m.dir),
  'pane-shape':           m => setShape(m.shape),
  'pane-shape-op':        m => setShapeOp(m.op),
  'pane-place-mode':      m => setPlaceMode(m.mode),
  'pane-material':        m => setMaterial(m.material),
  'pane-snap':            m => { snapToGrid = m.on; _paneToggle('btn-snap', m.on); },
  'pane-axislock':        m => { axisLock = m.on; _paneToggle('btn-axislock', m.on); },
  'pane-brush-size':      m => { brushSize = m.size; },
  'pane-door-size':       m => _paneField(m.id, m.value, 'change'),
  // ⚠ `input`, not `change`: that field is wired to oninput and ignores change entirely.
  'pane-corner-radius':   m => _paneField('fx-radius-num', m.radius, 'input'),

  'pane-reveal-all':  () => revealAllRooms(),
  'pane-shroud-all':  () => shroudAllRooms(),
  'pane-floorplan':   () => drawStoredFloorPlan(),
  // ⚠ The push to the TV goes with them: the picker's own handler runs in the DM window, which
  // has no Player of its own while two maps are up.
  'pane-fog-color':   m => { applyFogColor(m.pickedHex); syncFogColorToPlayer(m.pickedHex); },
  'pane-fog-tint':    m => { applyFogTintAlpha(m.alpha); syncFogColorToPlayer(fogPickedHex); },
  'pane-fog-feather': m => _paneField('fog-feather-num', m.radius, 'change'),
  'pane-fog-half':    m => _paneField('fog-half-alpha-num', m.pct, 'change'),
  'pane-anim':        m => applyPaneAnimParams(m),

  'pane-grid':      m => { applyGridConfig(m.config); commitGridChange(); },
  'pane-calibrate': m => armGridCalibration(!!m.on),

  // The Player pane. Each column drives its OWN Player window through its own controls.
  'pane-sync-view':         () => _paneClick('btn-sync-view'),
  'pane-send':              () => sendToPlayer(),
  'pane-auto-sync':         m => { if (autoSync !== m.on) _paneClick('btn-auto-sync'); },
  'pane-player-lock':       m => {
    minimapLocked = m.locked;
    if (playerWindow && !playerWindow.closed) {
      playerWindow.postMessage({ type: 'player-lock', locked: minimapLocked }, '*');
    }
  },
  'pane-player-view': m => {
    minimapSetView(m.view);
    if (playerWindow && !playerWindow.closed) {
      playerWindow.postMessage({ type: 'view-snap', ...m.view }, '*');
    }
  },
};

function _paneToggle(id, on) {
  const el = document.getElementById(id);
  if (el) el.classList.toggle('active', !!on);
}

// ⚠ Replays the control: these values are applied by a handler closed over their own field, so
// writing the variable alone skips the rebuild that follows.
function _paneField(id, value, evt) {
  const el = document.getElementById(id);
  if (!el) return;
  el.value = value;
  el.dispatchEvent(new Event(evt, { bubbles: true }));
}

function _paneClick(id) {
  const el = document.getElementById(id);
  if (el) el.click();
}

// One message carries every animation parameter, because every control that changes one ends in
// syncAnimToPlayer. A warp change is the only one needing the cloud frames rebuilt.
function applyPaneAnimParams(m) {
  const warpChanged = (m.cloudWarpStrength != null && m.cloudWarpStrength !== cloudWarpStrength)
                   || (m.cloudWarpRadius   != null && m.cloudWarpRadius   !== cloudWarpRadius);
  fogAnimSpeed      = m.fogAnimSpeed      ?? fogAnimSpeed;
  driftScale        = m.driftScale        ?? driftScale;
  cloudFrameSpeed   = m.cloudFrameSpeed   ?? cloudFrameSpeed;
  alphaPulseAmp     = m.alphaPulseAmp     ?? alphaPulseAmp;
  cloudWarpStrength = m.cloudWarpStrength ?? cloudWarpStrength;
  cloudWarpRadius   = m.cloudWarpRadius   ?? cloudWarpRadius;
  fogAnimEnabled    = m.fogAnimEnabled    ?? fogAnimEnabled;
  _paneToggle('btn-anim', fogAnimEnabled);
  if (fogAnimEnabled) startFogAnim(); else stopFogAnim();
  if (warpChanged) regenCloudFrames(); else syncAnimToPlayer();
}

function initPane() {
  reportPaneClicks();
  if (parent !== window) parent.postMessage({ type: 'pane-hello', pane: paneId }, '*');
  // A column opened empty has no scene menu of its own, so the card cannot tell the DM to use one.
  if (!new URLSearchParams(location.search).get('scene')) {
    const line = landing && landing.querySelector('p');
    if (line) line.innerHTML = 'Pick a map from <strong>Scenes</strong>';
  }
  window.addEventListener('message', e => {
    const msg = e.data;
    if (!msg || !msg.type) return;
    const handler = PANE_CONTROLS[msg.type];
    if (handler) handler(msg);
  });
}

function initPlayer() {
  fogAnimEnabled = true; // player view always animates
  // ⚠ A HALF WITH NO MAP SHOWS FOG ALONE: a second wordmark on one TV reads as a fault.
  if (paneId) {
    document.body.classList.add('stage-half');
    if (!mapOffscreen) startLoadingFog();
  }

  // Pre-generate the cloud texture while the player sits on the idle screen. The first
  // generateCloudFrames() blocks for a second or two, and doing it lazily inside loadFog shows
  // the players a fully-revealed map until it finishes.
  generateCloudFrames(512, CLOUD_FRAME_COUNT);

  if (playerReplyTarget()) playerReplyTarget().postMessage({
    type: 'PLAYER_READY', screenW: window.innerWidth, screenH: window.innerHeight,
  }, '*');


  // Relay this window's fullscreen state to the DM. It is native window fullscreen, driven
  // from main.js, so this window has nothing to read it from either — main pushes it here.
  if (window.electronAPI && window.electronAPI.onFullscreenState) {
    window.electronAPI.onFullscreenState((data) => {
      if (!playerReplyTarget()) return;
      playerReplyTarget().postMessage({
        type: 'PLAYER_FULLSCREEN', fullScreen: !!(data && data.fullScreen),
      }, '*');
    });
  }

  window.addEventListener('resize', () => {
    syncSize();
    if (playerReplyTarget()) playerReplyTarget().postMessage({
      type: 'PLAYER_SCREEN', screenW: window.innerWidth, screenH: window.innerHeight,
    }, '*');
    if (mapBitmap || mapOffscreen) {
      if (playerFollowDM && lastDMView) applyView(lastDMView);
      else fitToScreen();
      // The animated-map texture is sized from the viewport, so this is the one event
      // that has to reallocate it. Pan and zoom must not, and do not.
      if (mapVideo) initPlayerMapRegionTexture();
      viewportDirty = true;
      scheduleRender();
      // ⚠ THE MINIMAP CANNOT WORK THIS OUT: its zoom is px-per-map-unit on THIS canvas, so a
      // resize changes it and nothing else reports that. A divider drag resizes both halves.
      if (playerReplyTarget()) playerReplyTarget().postMessage({
        type: 'PLAYER_VIEW', mapCX: (getViewportSize().w / 2 - panX) / zoom,
        mapCY: (getViewportSize().h / 2 - panY) / zoom, zoom,
      }, '*');
    }
  });

  window.addEventListener('message', e => {
    const msg = e.data;
    if (!msg) return;
    startPlayerMapRetryOnce();   // anything from the DM means it is holding this window

    if (msg.type === 'fog-color') { handleFogColorMessage(msg); return; }

    if (msg.type === 'anim-params') {
      fogAnimSpeed      = msg.fogAnimSpeed      ?? fogAnimSpeed;
      driftScale        = msg.driftScale        ?? driftScale;
      cloudFrameSpeed   = msg.cloudFrameSpeed   ?? cloudFrameSpeed;
      alphaPulseAmp     = msg.alphaPulseAmp     ?? alphaPulseAmp;
      // ⚠ COMPARE, NEVER JUST CHECK THE FIELDS ARE PRESENT. Every scene load sends this message
      // carrying warp numbers the Player already has, and rebuilding all sixteen cloud frames on
      // each one is the freeze on opening the Player and on every switch.
      const warpChanged = (msg.cloudWarpStrength != null && msg.cloudWarpStrength !== cloudWarpStrength)
                       || (msg.cloudWarpRadius   != null && msg.cloudWarpRadius   !== cloudWarpRadius);
      if (warpChanged) {
        cloudWarpStrength = msg.cloudWarpStrength ?? cloudWarpStrength;
        cloudWarpRadius   = msg.cloudWarpRadius  ?? cloudWarpRadius;
        generateCloudFrames(512, CLOUD_FRAME_COUNT);
        cloudFramePos = 0;
        rebuildFogEffect();
      }
      fogAnimEnabled        = msg.fogAnimEnabled        ?? fogAnimEnabled;
      fogDirty = true;
      scheduleRender();
      if (fogAnimEnabled) startFogAnim(); else stopFogAnim();
      return;
    }

    if (msg.type === 'scene-transition') {
      if (msg.phase === 'out') {
        const fade = document.getElementById('scene-fade');
        // Marks the switch as landed: .dark tells an ordinary fog update from a switch in
        // progress, and the stamp starts the hold at full fog. Both belong to the moment the
        // cover completes, never to the start of the close.
        const covered = () => {
          fade.classList.add('dark');
          _sceneFadeStart = Date.now();
        };
        // Close the fog over the outgoing map. Only when there is no fog to close (nothing
        // loaded yet) does the flat blind stand in, and then there is nothing to wait for.
        if (closeFogOverMap(covered)) {
          fade.classList.remove('blind');
        } else {
          fade.classList.add('blind');
          snapFogCover(1);
          covered();
        }
      } else if (msg.phase === 'tint') {
        // The incoming scene's fog colour, sent ahead of its map. Eased into over what is
        // left of the close, so the colour change happens inside thickening fog.
        startFogColorEase(msg.pickedHex);
      }
      return;
    }

    // ⚠ A pre-warmed window's PLAYER_READY was dropped — the DM was not holding it yet.
    if (msg.type === 'player-hello') {
      if (playerReplyTarget()) playerReplyTarget().postMessage({
        type: 'PLAYER_READY', screenW: window.innerWidth, screenH: window.innerHeight,
      }, '*');
      return;
    }

    if (msg.type === 'player-lock') { playerInputLocked = msg.locked; return; }


    if (msg.type === 'view-snap') {
      playerFollowDM = true;
      notifyDMOfMode();
      if (mapOffscreen) startViewLerp(resolveView(msg));
      return;
    }

    if (msg.type === 'fullscreen') {
      if (window.electronAPI) window.electronAPI.toggleFullscreen();
      else if (document.fullscreenElement) document.exitFullscreen().catch(() => {});
      else document.documentElement.requestFullscreen().catch(() => {});
      return;
    }

    if (msg.type !== 'fog-update') return;
    if (msg.pickedHex) handleFogColorMessage({ pickedHex: msg.pickedHex, fogTintAlpha: msg.fogTintAlpha });
    // (retry loop in initPlayerMapRetry stops itself when mapOffscreen is set — no timer to clear)

    // Stay dark until map and fog are decoded and a render is queued, or the players see the old
    // scene or a half-applied fog. A first open has no 'out' phase, so the map would flash fog-less;
    // cover it the way a scene switch does, instantly, and let revealPlayer() ease it back.
    if (msg.mapUrl && fogCoverT < 1) {
      // The DM holds this payload back until the close has had its time, so normally this does
      // nothing. ⚠ If the cover has not landed, finish it NOW: everything below rewrites the map
      // size and camera, and doing that under a half-closed cover shows the swap.
      const fade = document.getElementById('scene-fade');
      fade.style.transition = 'none';
      fade.classList.toggle('blind', !(fogDataCanvas && cloudPattern));
      snapFogCover(1);              // also cancels the close, so the hold is stamped here
      fade.classList.add('dark');
      _sceneFadeStart = Date.now();
      void fade.offsetWidth;        // force reflow so the instant cover "sticks"
      fade.style.transition = '';   // restore so revealPlayer's removal animates
    }
    // ⚠ THE CARD IS THE LOADING STATE and sits ABOVE the cover (overlays.css). It holds through the
    // first map's decode; onPlayerMapShown() takes it down once the map is on screen.
    if (mapOffscreen) landing.style.display = 'none';
    else if (msg.mapUrl) startLoadingFog();

    if (msg.view) lastDMView = msg.view;

    // Freeze the fog BEFORE anything the cloud transform reads changes. mapWidth is the first
    // of them; fitToScreen's camera and the new fogDataCanvas follow further down.
    if (msg.mapUrl && fogCoverT >= 1) freezeCloudTransform();

    mapWidth  = msg.mapWidth;
    mapHeight = msg.mapHeight;
    // Effects arrive as the polygon records themselves, so there is nothing to convert. ⚠ An empty
    // list is meaningful, which is why this checks for undefined rather than truthiness.
    if (msg.effects !== undefined) setEffects(msg.effects);
    if (msg.gridEnabled !== undefined) {
      gridEnabled   = msg.gridEnabled;
      gridSize      = msg.gridSize      || gridSize;
      gridOffsetX   = msg.gridOffsetX   ?? gridOffsetX;
      gridOffsetY   = msg.gridOffsetY   ?? gridOffsetY;
      gridColor     = msg.gridColor     || gridColor;
      gridOpacity   = msg.gridOpacity   ?? gridOpacity;
      gridMode      = msg.gridMode      || gridMode;
      gridLineWidth = msg.gridLineWidth ?? gridLineWidth;
      gridDirty   = true;
    }

    // revealPlayer() is defined in scenes.js — enforces SCENE_FADE_MIN_MS floor then lifts the cover.

    // skipTransition: scene switches must not blend old fog into new — show new state directly.
    const loadFog = (src, skipTransition) => new Promise(resolve => {
      const img = new Image();
      img.onerror = () => resolve();
      img.onload = () => {
        // BOTH dimensions, never the width alone: two maps can share a width and differ in
        // height, and the kept canvas then squashes the incoming mask into the old aspect.
        if (!fogDataCanvas ||
            fogDataCanvas.width  !== Math.ceil(mapWidth  / FOG_SCALE) ||
            fogDataCanvas.height !== Math.ceil(mapHeight / FOG_SCALE)) {
          fogDataCanvas = document.createElement('canvas');
          fogDataCanvas.width  = Math.ceil(mapWidth  / FOG_SCALE);
          fogDataCanvas.height = Math.ceil(mapHeight / FOG_SCALE);
          fogDataCtx = fogDataCanvas.getContext('2d');
        }
        fogDataCtx.clearRect(0, 0, fogDataCanvas.width, fogDataCanvas.height);
        fogDataCtx.drawImage(img, 0, 0, fogDataCanvas.width, fogDataCanvas.height);
        if (!cloudPattern) generateCloudFrames(512, CLOUD_FRAME_COUNT);
        if (!skipTransition && msg.fogChanged) startFogTransition(!!msg.isShroud);
        rebuildFogEffect();
        // Now this scene has a cloud pattern, the flat blind hands over to real fog, which is what
        // gets the session's first map onto fog instead of navy. The cover is already at 1, so only
        // what draws it changes.
        // ⚠ GATED ON A TRANSITION BEING UP: every ordinary fog update lands here too, and touching
        // the cover on those blanks the players' screen mid-game.
        const fadeEl = document.getElementById('scene-fade');
        if (fadeEl.classList.contains('dark') && fogDataCanvas && cloudPattern) {
          fadeEl.classList.remove('blind');
        }
        startFogAnim();
        // The cloud transform stays PINNED here. It is re-anchored onto the new scene at the
        // end of the hold at full fog, one frame before the reveal — see openFogFromCover().
        resolve();
      };
      img.src = src;
    });

    if (msg.mapUrl && msg.mapType === 'video') {
      dropPendingPlayerVideo();
      cleanupVideo();

      // ⚠ Play from a PRIVATE in-memory copy of the clip, never the file:// path the DM is already
      // streaming. Two <video> elements on one file starve Chromium's media pipeline and both
      // windows stall. Falls back to the shared URL if the in-memory read fails.
      const _gen = ++_playerVideoGen;

      const beginPlayerVideo = (srcUrl) => {
        if (_gen !== _playerVideoGen) {          // a newer scene switch superseded this
          if (srcUrl && srcUrl.startsWith('blob:')) URL.revokeObjectURL(srcUrl);
          return;
        }
        mapVideoUrl = srcUrl;
        const video = createPlayerVideoElement(container);
        _playerPendingVideo = video;
        let settled = false;
        video.onerror = () => {
          if (settled) return;
          settled = true;
          if (_playerPendingVideo === video) _playerPendingVideo = null;
          video.onerror = null; video.oncanplay = null;
          video.pause(); video.src = '';
          if (video.parentNode) video.parentNode.removeChild(video);
          cleanupVideo(); revealPlayer();
        };
        video.oncanplay = function() {
          if (settled) return;
          settled = true;
          video.onerror = null; video.oncanplay = null;

          function finishPlayerVideo() {
            const extractCanvas = document.createElement('canvas');
            extractCanvas.width = mapWidth; extractCanvas.height = mapHeight;
            extractCanvas.getContext('2d').drawImage(video, 0, 0, mapWidth, mapHeight);
            if (mapBitmap) { mapBitmap.close(); mapBitmap = null; }
            mapOffscreen = extractCanvas;
            // mapVideo has to be live before the texture is built: both
            // initPlayerMapRegionTexture and the sync tick read it.
            // ⚠ Pending ends HERE, not at oncanplay: the seek above still reads the source.
            if (_playerPendingVideo === video) _playerPendingVideo = null;
            mapVideo = video;
            // Refresh from the video every rendered frame, driven by the PixiJS render
            // ticker so it never freezes between viewport changes.
            var _texVideoTime = -1, _texPanX = NaN, _texPanY = NaN, _texZoom = NaN;
            pixiStartVideoTextureSync(function() {
              if (!mapVideo || !playerMapTexCtx || mapVideo.readyState < 2) return;
              var t = mapVideo.currentTime;
              // Pan and zoom join the dedup key, because the texture holds a region: on a paused
              // video the frame never advances and the map would go stale under a moving camera.
              if (t === _texVideoTime && panX === _texPanX && panY === _texPanY && zoom === _texZoom) return;
              _texVideoTime = t; _texPanX = panX; _texPanY = panY; _texZoom = zoom;
              refreshPlayerMapRegion();
            });
            attachVideoListeners(video);
            fitToScreen();
            if (playerFollowDM && msg.view) applyView(msg.view);
            // After the camera is settled, so the first texture holds the region the players will
            // see. Viewport-sized, never map-sized — the same cost on any map, and that figure is
            // also the per-frame GPU upload.
            initPlayerMapRegionTexture();
            loadFog(msg.fogDataUrl, !!msg.sceneChange).then(() => {
              // loadFog already ran rebuildFogEffect(), which syncs the fog pass to the GPU.
              viewportDirty = true;
              scheduleRender();
              video.play().then(() => startVideoLoop()).catch(() => {});
              revealPlayer();
            });
          }

          video.onseeked = function() { video.onseeked = null; finishPlayerVideo(); };
          video.currentTime = 0.001;
          setTimeout(() => { if (video.onseeked) { video.onseeked = null; finishPlayerVideo(); } }, 2000);
        };
        video.src = srcUrl;
      };

      if (window.electronAPI && window.electronAPI.readVideoFile && msg.mapSceneId) {
        const _mime = /\.mp4(\?|$)/i.test(msg.mapUrl) ? 'video/mp4' : 'video/webm';
        window.electronAPI.readVideoFile(msg.mapSceneId).then(function(buf) {
          if (buf) {
            // The DM's own URL goes UNUSED here, and for a legacy scene it is a blob: URL holding
            // the whole video. Nothing else releases it, so it is released at this one moment the
            // Player knows it will not be read.
            if (/^blob:/.test(msg.mapUrl)) URL.revokeObjectURL(msg.mapUrl);
            beginPlayerVideo(URL.createObjectURL(new Blob([buf], { type: _mime })));
          } else {
            beginPlayerVideo(msg.mapUrl);   // read failed — fall back to the shared file
          }
        }).catch(function() { beginPlayerVideo(msg.mapUrl); });
      } else {
        beginPlayerVideo(msg.mapUrl);
      }
    } else if (msg.mapUrl) {
      dropPendingPlayerVideo();
      cleanupVideo();
      // ⚠ THE FOG WAITS FOR THE MAP. Starting both decodes together saves a few tens of ms and
      // costs correctness: a map that fails to decode leaves the previous one on screen, and the
      // incoming scene's reveals would be punched into it - ground the players must not see.
      const img = new Image();
      img.onerror = () => { URL.revokeObjectURL(msg.mapUrl); revealPlayer(); };
      img.onload = () => {
        mapOffscreen = document.createElement('canvas');
        mapOffscreen.width  = mapWidth;
        mapOffscreen.height = mapHeight;
        mapOffscreen.getContext('2d').drawImage(img, 0, 0);
        URL.revokeObjectURL(msg.mapUrl);
        if (mapBitmap) { mapBitmap.close(); mapBitmap = null; }
        pixiSetMap(prepareTextureCanvas(mapOffscreen, mapWidth, mapHeight), mapWidth, mapHeight);
        fitToScreen();
        if (playerFollowDM && msg.view) applyView(msg.view);
        loadFog(msg.fogDataUrl, !!msg.sceneChange).then(() => {
          // loadFog already ran rebuildFogEffect(), which syncs the fog pass to the GPU.
          viewportDirty = true;
          scheduleRender();
          revealPlayer();
        });
      };
      img.src = msg.mapUrl;
    } else {
      if (playerFollowDM && msg.view) applyView(msg.view);
      loadFog(msg.fogDataUrl, !!msg.sceneChange).then(() => {
        viewportDirty = true;
        scheduleRender();
        revealPlayer();
      });
    }
  });

  // Player pan/zoom (free-look)
  let playerIsPanning = false;
  let playerPanStartX, playerPanStartY, playerPanStartPanX, playerPanStartPanY;
  let _playerViewThrottleTs = 0;
  function _postPlayerView() {
    const now = performance.now();
    if (now - _playerViewThrottleTs < 100) return;
    _playerViewThrottleTs = now;
    if (!playerReplyTarget()) return;
    const { w: vpW, h: vpH } = getViewportSize();
    playerReplyTarget().postMessage({
      type: 'PLAYER_VIEW',
      mapCX: (vpW / 2 - panX) / zoom,
      mapCY: (vpH / 2 - panY) / zoom,
      zoom,
    }, '*');
  }

  container.addEventListener('mousedown', e => {
    if (playerInputLocked) return;
    if (!mapOffscreen) return;
    playerIsPanning = true;
    playerPanStartX = e.clientX; playerPanStartY = e.clientY;
    playerPanStartPanX = panX;   playerPanStartPanY = panY;
    e.preventDefault();
  });

  container.addEventListener('mousemove', e => {
    if (playerInputLocked) return;
    if (!playerIsPanning || !mapOffscreen) return;
    const dx = e.clientX - playerPanStartX;
    const dy = e.clientY - playerPanStartY;
    if (playerFollowDM && (Math.abs(dx) > 4 || Math.abs(dy) > 4)) {
      playerFollowDM = false;
      notifyDMOfMode();
    }
    panX = playerPanStartPanX + dx;
    panY = playerPanStartPanY + dy;
    if (!playerFollowDM) _postPlayerView();
    viewportDirty = true;
    scheduleRender();
  });

  window.addEventListener('mouseup', () => { playerIsPanning = false; });

  container.addEventListener('wheel', e => {
    e.preventDefault();
    if (playerInputLocked) return;
    if (!mapOffscreen) return;
    const factor  = e.deltaY < 0 ? ZOOM_FACTOR : 1 / ZOOM_FACTOR;
    const newZoom = Math.max(0.02, Math.min(20, zoom * factor));
    const rect    = container.getBoundingClientRect();
    const mx = e.clientX - rect.left;
    const my = e.clientY - rect.top;
    panX = mx - (mx - panX) * (newZoom / zoom);
    panY = my - (my - panY) * (newZoom / zoom);
    zoom = newZoom;
    if (playerFollowDM) {
      playerFollowDM = false;
      notifyDMOfMode();
    }
    _postPlayerView();
    viewportDirty = true;
    scheduleRender();
  }, { passive: false });

  initStress();
  initMemProbe();
}
